name: Push-to-EC2 instance

on:
  push:
    branches:
      - main, master

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@1.2.0
        with:
          host: 65.2.121.145
          username: ubuntu
          password: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami
