name: Push-to-EC2 instance

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 65.2.121.145
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd aws-ec2-cicd-demo
            git pull 
            npm install
            npm run build
            npm run start

